export const achievements = [
  {
    id: 1,
    title: "Doomsdale - HTML Basics",
    description: "Complete the HTML Basics stage",
    lvl: 3,
    coins: 100,
  },
  {
    id: 2,
    title: "Terraquill - CSS Styling",
    description: "Complete the CSS Styling stage",
    lvl: 5,
    coins: 200,
  },
  {
    id: 3,
    title: "Nemorosa - HTML & CSS Integration",
    description: "Complete the HTML & CSS Integration stage",
    lvl: 7,
    coins: 300,
  },
  {
    id: 4,
    title: "Rimegate - JavaScript Fundamentals",
    description: "Complete the JavaScript Fundamentals stage",
    lvl: 9,
    coins: 400,
  },
  {
    id: 5,
    title: "Sunfire Isle - DOMination",
    description: "Complete the DOMination stage",
    lvl: 11,
    coins: 500,
  },
  {
    id: 6,
    title: "Learn the basics of HTML",
    description: "Complete the learning stage of HTML",
    lvl: 1,
    coins: 50,
  },
  {
    id: 7,
    title: "Learn the basics of CSS",
    description: "Complete the learning stage of CSS",
    lvl: 1,
    coins: 50,
  },
  {
    id: 8,
    title: "Learn the basics of HTML and CSS integration",
    description: "Complete the learning stage of HTML and CSS integration",
    lvl: 1,
    coins: 50,
  },
  {
    id: 9,
    title: "Learn the basics of JavaScript",
    description: "Complete the learning stage of JavaScript",
    lvl: 1,
    coins: 50,
  },
  {
    id: 10,
    title: "Learn the basics of DOM manipulation",
    description: "Complete the learning stage of DOM manipulation",
    lvl: 1,
    coins: 50,
  },
  {
    id: 11,
    title: "Slayed the Boss of Doomsdale",
    description: "Defeat the boss of Doomsdale stage",
    lvl: 3,
    coins: 100,
  },
  {
    id: 12,
    title: "Slayed the Boss of Terraquill",
    description: "Defeat the boss of Terraquill stage",
    lvl: 3,
    coins: 200,
  },
  {
    id: 13,
    title: "Slayed the Boss of Nemorosa",
    description: "Defeat the boss of Nemorosa stage",
    lvl: 3,
    coins: 300,
  },
  {
    id: 14,
    title: "Slayed the Boss of Rimegate",
    description: "Defeat the boss of Rimegate stage",
    lvl: 3,
    coins: 400,
  },
  {
    id: 15,
    title: "Slayed the Boss of Sunfire Isle",
    description: "Defeat the boss of Sunfire Isle stage",
    lvl: 3,
    coins: 500,
  },
];
