export const CSS_GUIDEBOOK = [
  {
    text: "Example of changing the color and the font size of the <p> element external CSS",
    code: "/guidebook/css/img-1.png",
    width: 240,
    height: 161,
  },
  {
    text: "Type selector: element",
    code: "/guidebook/css/img-2.png",
    width: 212,
    height: 138,
  },
  {
    text: "Type selector: class",
    code: "/guidebook/css/img-3.png",
    width: 210,
    height: 141,
  },
  {
    text: "Type selector: id",
    code: "/guidebook/css/img-4.png",
    width: 261,
    height: 137,
  },
  {
    text: "Making a box",
    code: "/guidebook/css/img-5.png",
    width: 342,
    height: 190,
  },
  {
    text: "Positioning an element",
    code: "/guidebook/css/img-6.png",
    width: 295,
    height: 190,
  },
  {
    text: "Making a Flexbox Container",
    code: "/guidebook/css/img-7.png",
    width: 240,
    height: 137,
  },
  {
    text: "Making a Grid Container",
    code: "/guidebook/css/img-8.png",
    width: 482,
    height: 187,
  },
  {
    text: "Placing items on Grid Container",
    code: "/guidebook/css/img-9.png",
    width: 312,
    height: 165,
  },
  {
    text: "Styling a background and adjust the size and other attributes",
    code: "/guidebook/css/img-10.png",
    width: 472,
    height: 238,
  },
  {
    text: "Align a text",
    code: "/guidebook/css/img-11.png",
    width: 292,
    height: 136,
  },
  {
    text: "Align an element",
    code: "/guidebook/css/img-12.png",
    width: 417,
    height: 187,
  },
  {
    text: "Hover an element",
    code: "/guidebook/css/img-13.png",
    width: 222,
    height: 137,
  },
  {
    text: "Active an element",
    code: "/guidebook/css/img-14.png",
    width: 333,
    height: 137,
  },
  {
    text: "Focus an element",
    code: "/guidebook/css/img-15.png",
    width: 325,
    height: 137,
  },
];
