export const HTMLCSSJS_GUIDEBOOK = [
  {
    text: "Example of DOM Manipulation:",
    code: "/guidebook/htmlcssjs/img-1.png",
    width: 731,
    height: 433,
  },
  {
    text: "Example of Modifying Elements:",
    code: "/guidebook/htmlcssjs/img-2.png",
    width: 806,
    height: 236,
  },
  {
    text: "Example of Creating Elements:",
    code: "/guidebook/htmlcssjs/img-3.png",
    width: 648,
    height: 212,
  },
  {
    text: "HTML Forms:",
    code: "/guidebook/htmlcssjs/img-4.png",
    width: 518,
    height: 185,
  },
  {
    text: "Internal JavaScript:",
    code: "/guidebook/htmlcssjs/img-5.png",
    width: 787,
    height: 461,
  },
  {
    text: "Event Listener:",
    code: "/guidebook/htmlcssjs/img-6.png",
    width: 590,
    height: 183,
  },
  {
    text: "Click Event:",
    code: "/guidebook/htmlcssjs/img-7.png",
    width: 671,
    height: 460,
  },
  {
    text: "Mouseover Event",
    code: "/guidebook/htmlcssjs/img-8.png",
    width: 732,
    height: 486,
  },
  {
    text: "Mouseout Event:",
    code: "/guidebook/htmlcssjs/img-9.png",
    width: 761,
    height: 436,
  },
  {
    text: "Keydown Event:",
    code: "/guidebook/htmlcssjs/img-10.png",
    width: 632,
    height: 486,
  },
  {
    text: "Event Key Example:",
    code: "/guidebook/htmlcssjs/img-11.png",
    width: 638,
    height: 512,
  },
  {
    text: "Keyup Event:",
    code: "/guidebook/htmlcssjs/img-12.png",
    width: 630,
    height: 486,
  },
  {
    text: "Submit Event:",
    code: "/guidebook/htmlcssjs/img-13.png",
    width: 473,
    height: 660,
  },
  {
    text: "Inline Event Handlers",
    code: "/guidebook/htmlcssjs/img-14.png",
    width: 685,
    height: 85,
  },
  {
    text: "Mouse Events:",
    code: "/guidebook/htmlcssjs/img-15.png",
    width: 830,
    height: 286,
  },
  {
    text: "Keyboard Events:",
    code: "/guidebook/htmlcssjs/img-16.png",
    width: 655,
    height: 190,
  },
  {
    text: "Form Events:",
    code: "/guidebook/htmlcssjs/img-17.png",
    width: 775,
    height: 185,
  },
  {
    text: "Focus Events:",
    code: "/guidebook/htmlcssjs/img-18.png",
    width: 562,
    height: 162,
  },
  {
    text: "Example of using event handlers (onclick, onsubmit and etc.)",
    code: "/guidebook/htmlcssjs/img-19.png",
    width: 693,
    height: 236,
  },
];
