export const HTML_GUIDEBOOK = [
  {
    text: "Basic Structure of HTML",
    code: "/guidebook/html/img-1.png",
    width: 397,
    height: 292,
  },
  {
    text: "Creating a paragraph tags",
    code: "/guidebook/html/img-2.png",
    width: 356,
    height: 88,
  },
  {
    text: "Creating emphasis and strong tags",
    code: "/guidebook/html/img-3.png",
    width: 431,
    height: 117,
  },
  {
    text: "Creating heading tags from level 1 to 6",
    code: "/guidebook/html/img-4.png",
    width: 291,
    height: 217,
  },
  {
    text: "Creating line break tags (<br>)",
    code: "/guidebook/html/img-5.png",
    width: 591,
    height: 87,
  },
  {
    text: "Creating horizontal line (<hr>)",
    code: "/guidebook/html/img-6.png",
    width: 413,
    height: 166,
  },
  {
    text: "Creating a comment",
    code: "/guidebook/html/img-7.png",
    width: 341,
    height: 88,
  },
  {
    text: "Creating images",
    code: "/guidebook/html/img-8.png",
    width: 542,
    height: 90,
  },
  {
    text: "Creating ordered list",
    code: "/guidebook/html/img-9.png",
    width: 243,
    height: 165,
  },
  {
    text: "Creating unordered list",
    code: "/guidebook/html/img-10.png",
    width: 252,
    height: 160,
  },
  {
    text: "Creating small text",
    code: "/guidebook/html/img-11.png",
    width: 448,
    height: 85,
  },
  {
    text: "Creating div",
    code: "/guidebook/html/img-12.png",
    width: 238,
    height: 137,
  },
  {
    text: "Creating links",
    code: "/guidebook/html/img-13.png",
    width: 742,
    height: 88,
  },
  {
    text: "Creating tables with header, rows and data",
    code: "/guidebook/html/img-14.png",
    width: 297,
    height: 311,
  },
];
