export const JS_GUIDEBOOK = [
  {
    text: "Console Output:",
    code: "/guidebook/js/img-1.png",
    width: 361,
    height: 88,
  },
  {
    text: "Variables:",
    code: "/guidebook/js/img-2.png",
    width: 386,
    height: 112,
  },
  {
    text: "Conditional Statements:",
    code: "/guidebook/js/img-3.png",
    width: 443,
    height: 235,
  },
  {
    text: "Loops:",
    code: "/guidebook/js/img-4.png",
    width: 373,
    height: 137,
  },
  {
    text: "While loop:",
    code: "/guidebook/js/img-5.png",
    width: 250,
    height: 186,
  },
  {
    text: "Functions:",
    code: "/guidebook/js/img-6.png",
    width: 468,
    height: 186,
  },
  {
    text: "Arrow Functions: A compact way to write functions.",
    code: "/guidebook/js/img-7.png",
    width: 756,
    height: 137,
  },
  {
    text: "Destructuring: Using the {a, b} = operator",
    code: "/guidebook/js/img-8.png",
    width: 623,
    height: 187,
  },
  {
    text: "Destructuring: Using the [a, b] = operator",
    code: "/guidebook/js/img-9.png",
    width: 567,
    height: 187,
  },
  {
    text: "Rest operator:",
    code: "/guidebook/js/img-10.png",
    width: 620,
    height: 163,
  },
  {
    text: "Spread operator:",
    code: "/guidebook/js/img-11.png",
    width: 520,
    height: 138,
  },
  {
    text: "Parameters and return statement:",
    code: "/guidebook/js/img-12.png",
    width: 522,
    height: 188,
  },
  {
    text: "Concatenation:",
    code: "/guidebook/js/img-13.png",
    width: 563,
    height: 142,
  },
  {
    text: "Arrays:",
    code: "/guidebook/js/img-14.png",
    width: 728,
    height: 91,
  },
  {
    text: "Pop, Push, Shift and Unshift Array Methods:",
    code: "/guidebook/js/img-15.png",
    width: 632,
    height: 87,
  },
  {
    text: "Push Method Example:",
    code: "/guidebook/js/img-16.png",
    width: 663,
    height: 117,
  },
  {
    text: "Pop Method Example:",
    code: "/guidebook/js/img-17.png",
    width: 653,
    height: 162,
  },
  {
    text: "Shift Method Example:",
    code: "/guidebook/js/img-18.png",
    width: 657,
    height: 163,
  },
  {
    text: "Unshift Method Example:",
    code: "/guidebook/js/img-19.png",
    width: 757,
    height: 112,
  },
  {
    text: "Map Method:",
    code: "/guidebook/js/img-20.png",
    width: 662,
    height: 111,
  },
  {
    text: "Filter Method:",
    code: "/guidebook/js/img-21.png",
    width: 726,
    height: 112,
  },
  {
    text: "Reduce Method:",
    code: "/guidebook/js/img-22.png",
    width: 602,
    height: 260,
  },
  {
    text: "Find Method:",
    code: "/guidebook/js/img-23.png",
    width: 702,
    height: 283,
  },
  {
    text: "Objects:",
    code: "/guidebook/js/img-24.png",
    width: 612,
    height: 165,
  },
  {
    text: "Obect.keys Method:",
    code: "/guidebook/js/img-25.png",
    width: 612,
    height: 263,
  },
  {
    text: "Object.values Method:",
    code: "/guidebook/js/img-26.png",
    width: 617,
    height: 262,
  },
  {
    text: "Object.entries Method:",
    code: "/guidebook/js/img-27.png",
    width: 733,
    height: 261,
  },
];
